services:
  ffc-ahwr-backoffice:
    build:
      context: .
      target: production
    image: ffc-ahwr-backoffice
    container_name: ffc-ahwr-backoffice
    environment:
      AADAR_ENABLED: ${AADAR_ENABLED:-true}
      AADAR_CLIENT_SECRET: ${AADAR_CLIENT_SECRET:-notset}
      AADAR_CLIENT_ID: ${AADAR_CLIENT_ID:-notset}
      AADAR_REDIRECT_URL: ${AADAR_REDIRECT_URL:-http://localhost:3002/authenticate}
      AADAR_TENANT_ID: ${AADAR_TENANT_ID:-notset}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
      AHWR_SERVICE_URI: http://localhost:3002
      SERVICE_VERSION: ${SERVICE_VERSION:-1.0.0}
      AHWR_APPLICATION_BACKEND_URL: http://ahwr-application-backend:3001/api
      DISPLAY_PAGE_SIZE: 20
      ON_HOLD_APP_PROCESS_ENABLED: "true"
      ON_HOLD_APP_PROCESS_SCHEDULE: "0 0 * * 2-5"
      DATA_REDACTION_PROCESS_ENABLED: "true"
      DATA_REDACTION_PROCESS_SCHEDULE: "0 0 * * 2-5"
      SUPER_ADMINS: ${SUPER_ADMINS}
