services:
  ahwr-backoffice-ui:
    build:
      context: .
      target: production
    image: ahwr-backoffice-ui
    container_name: ahwr-backoffice-ui
    environment:
      AADAR_ENABLED: ${AADAR_ENABLED:-false}
      AADAR_CLIENT_SECRET: ${AADAR_CLIENT_SECRET:-notset}
      AADAR_CLIENT_ID: ${AADAR_CLIENT_ID:-notset}
      AADAR_REDIRECT_URL: ${AADAR_REDIRECT_URL:-http://localhost:3002/authenticate}
      AADAR_AUTHORITY_URL: ${AADAR_AUTHORITY_URL:-http://notset}
      COOKIE_PASSWORD: who-likes-cookies-i-like-cookies-everybody-likes-cookies
      REDIS_HOST: redis
      REDIS_USERNAME: ""
      REDIS_PASSWORD: ""
      AHWR_SERVICE_URI: http://localhost:3002
      SERVICE_VERSION: ${SERVICE_VERSION:-1.0.0}
      AHWR_APPLICATION_BACKEND_URL: http://ahwr-application-backend:3001/api
      AHWR_PAYMENT_PROXY_URL: http://ahwr-payment-proxy:3001/api
      AHWR_MESSAGE_GENERATOR_URL: http://ahwr-message-generator:3001/api
      AHWR_DOCUMENT_GENERATOR_URL: http://ahwr-document-generator-backend:3008/api
      DISPLAY_PAGE_SIZE: 20
      SUPER_ADMINS: ${SUPER_ADMINS}
